### ISSUE TITLE
Resizable Image with .aspectRatio(contentMode: .fill) not correctly displayed

### ISSUE THREAD

**Issue by palle-k** [exyte/Grid#4]
When using a resizable `Image` with `.aspectRatio(contentMode: .fill)`, the image may not be correctly displayed.

Here's a code example to reproduce the issue:

```swift
Grid(tracks: 3) {
    ForEach(0 ..< 7) { i in
        Image("ExampleImage")
        .resizable()
        .aspectRatio(contentMode: .fill)
    }
}
.gridContentMode(.scroll)
```

With `ForEach(0 ..< 1)`, the image fills the whole width of the grid container (instead of just one column).

The more rows are added, the more zoomed in the images become. 

With 10 rows, only a single pixel of the image is visible, filling the entire screen.

**Comment by palle-k** [comment]
I guess adding a max height would fix the issue partially, with the other part being `.gridCellClip(shape:)`

**Comment by EfraimB** [comment]
Why don't you merge this into the master? What good a grid library view is if you can't display images properly?

**Comment by denis-obukhov** [comment]
@EfraimB 
This seems to be fixed in the latest Xcodes. It should be appropriate to use `.fit` content mode in such cases.

Code:
```swift
	var body: some View {
		Grid(tracks: 3) {
				ForEach(0 ..< 7) { i in
					Image("apple")
						.resizable()
						.aspectRatio(contentMode: .fit)
				}
		}
		.gridContentMode(.scroll)
	}
```

Here are my results for the preview canvas:
![image](https://user-images.githubusercontent.com/63708833/92064412-a4f4c180-edc7-11ea-8d3b-e1573186f128.png)

**But in runtime both Xcode builds work as intended.**
Tested both on iOS 14.0 and iOS 13.6
If you are still having an issue please provide the code for reproducing.
